[package]
name = "rust_native_graphing_calculator"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.29", features = ["default_fonts", "wgpu"] }
egui = "0.29"
egui_plot = "0.29"
meval = "0.2"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
directories = "5"
